version: 2
before:
  hooks:
    - go mod tidy
builds:
  - id: distrohop
    env:
      - CGO_ENABLED=0
    binary: distrohop
    goos:
      - linux
    goarch:
      - amd64
      - '386'
      - arm64
      - arm
      - riscv64
archives:
  - files:
    - distrohop.service
nfpms:
  - id: distrohop
    description: "A utility for correlating and identifying equivalent software packages across different Linux distributions"
    homepage: 'https://gitea.elara.ws/Elara6331/distrohop'
    maintainer: 'Elara Ivy <elara@elara.ws>'
    license: AGPLv3
    formats:
      - deb
      - rpm
      - archlinux
    provides:
      - distrohop
    conflicts:
      - distrohop
    contents:
      - src: distrohop.service
        dst: /etc/systemd/system/distrohop.service
aurs:
  - name: distrohop-bin
    homepage: 'https://gitea.elara.ws/Elara6331/distrohop'
    description: "A utility for correlating and identifying equivalent software packages across different Linux distributions"
    maintainers:
      - 'Elara Ivy <elara@elara.ws>'
    license: AGPLv3
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/distrohop-bin.git'
    provides:
      - distrohop
    conflicts:
      - distrohop
    package: |-
      # binaries
      install -Dm755 ./distrohop "${pkgdir}/usr/bin/distrohop"
      
      # services
      install -Dm644 ./distrohop.service "${pkgdir}/etc/systemd/system/distrohop.service"
release:
  gitea:
    owner: Elara6331
    name: distrohop
gitea_urls:
  api: 'https://gitea.elara.ws/api/v1/'
  download: 'https://gitea.elara.ws'
  skip_tls_verify: false
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc