labels:
  platform: linux/amd64

steps:
  - name: docker
    image: gitea.elara.ws/elara6331/builder
    commands:
      - registry-login
      - ko build -B --platform=linux/amd64,linux/arm64,linux/riscv64 -t latest,${CI_COMMIT_TAG} --sbom=none
    environment:
      REGISTRY: gitea.elara.ws
      REGISTRY_USERNAME: Elara6331
      KO_DOCKER_REPO: gitea.elara.ws/elara6331
      KO_DEFAULTBASEIMAGE: gitea.elara.ws/elara6331/static-root
      REGISTRY_PASSWORD:
        from_secret: registry_password
    when:
      event: tag
  
  - name: release
    image: goreleaser/goreleaser
    commands:
      - goreleaser release
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      AUR_KEY:
        from_secret: aur_key
    when:
      event: tag